### ISSUE TITLE
not working if TODO comment is on same line as the code

### ISSUE THREAD

**Issue by byteface** [kevinsawade/python-todo-to-issue#38]
Hi, I tried this but no issues are being created

https://github.com/byteface/sharpshooter/blob/master/sharpshooter/__init__.py

I suspected because I use uppercase. but when i made it lower nothign happens. i also added the colon. but still nothing. Does it need to be at the begginning of the line?

**Comment by kevinsawade** [comment]
Hi byteface,

thank you for using my repository. You are right, the todos (capitalization doesn't matter) need to be at the start of lines.

If I run your file through the `extract_todos_from_file()` function, I get the following output:

```python
import requests
from main import extract_todos_from_file

r = requests.get('https://raw.githubusercontent.com/byteface/sharpshooter/master/sharpshooter/__init__.py')
extract_todos_from_file(r.text)
```

Output:
```python
['- this aint dont yet', '- error if not divisible by 4']
```

Which is expected, as they are at the start of lines.

Note: Todos are only picked up, when they are added via a commit. Todos which have been in your repository before you added the action are not picked up.  If you want, you can try and move one of the todos to a new line and commit and check whether an Issue is raised.

Hope this helps.

**Comment by kevinsawade** [comment]
Otherwise I can recommend alstr's repository (https://github.com/alstr/todo-to-issue-action), which does the same thing (for more languages than python).

Key difference: alstr's code doesn't pick up todos from docstrings:

```python
def myfunc():
"""Short description of myfunc.

Longer description of myfunc.

Todo:
    * Actually write that function.

"""
pass
```

**Comment by byteface** [comment]
I usually just grep 'todo' out to a txt file but automating tickets is good idea.

Thanks for replying. the regex you're using performs correctly even on half lines when i check in a regex validator.

So I think the issue is line on 934 only takes lines that start with  # so any inline (or on the line) comments get missed. (without actually pulling the code)

Arguably, it may be a non-standard for me to be doing so. So you might be fine to leave it. But It would be nice if it could pick up todos written on the same line as the code. I guess I'll leave it up to you.

thanks also for sharing the snippet.

**Comment by kevinsawade** [comment]
I like the idea of also picking up todos after code lines. I will see how to implement this feature. I could couple that with an option in the `workflow.yml`. Something like:

```yaml
- name: Create Issues ✔️
        uses: kevinsawade/python-todo-to-issue@latest
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHECK_ONLY_COMMENT_LINES: ${{ false }}
```

**Comment by kevinsawade** [comment]
With the latest version (1.0.3) you can change the workflow.yaml to include a `INCLUDE_TODO_AFTER_CODE_LINE`:

```yaml
- name: Create Issues ✔️
  uses: kevinsawade/python-todo-to-issue@latest
  with:
    TOKEN: ${{ secrets.GITHUB_TOKEN }}
    INCLUDE_TODO_AFTER_CODE_LINE
```

This should include your todos. Please reopen if it does not work.
